[target.x86_64-pc-windows-gnu]
pre-build = [
  "apt update",
  "apt install -y clang libclang-dev nasm"
]

[target.x86_64-unknown-linux-gnu]
zig = "2.17"
pre-build = [
  "apt update",
  "DEBIAN_FRONTEND=noninteractive apt install -y clang libclang-dev nasm curl xz-utils",
  "curl -sSfL https://github.com/rust-cross/cargo-zigbuild/releases/latest/download/cargo-zigbuild-installer.sh | CARGO_HOME=/usr/local sh"
]

[target.aarch64-unknown-linux-gnu]
zig = "2.17"
pre-build = [
  "apt update",
  "DEBIAN_FRONTEND=noninteractive apt install -y clang libclang-dev nasm curl xz-utils",
  "curl -sSfL https://github.com/rust-cross/cargo-zigbuild/releases/latest/download/cargo-zigbuild-installer.sh | CARGO_HOME=/usr/local sh"
]

[target.mips-unknown-linux-gnu]
image = "ghcr.io/cross-rs/mips-unknown-linux-gnu:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips-unknown-linux-musl]
image = "ghcr.io/cross-rs/mips-unknown-linux-musl:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mipsel-unknown-linux-gnu]
image = "ghcr.io/cross-rs/mipsel-unknown-linux-gnu:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mipsel-unknown-linux-musl]
image = "ghcr.io/cross-rs/mipsel-unknown-linux-musl:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64-unknown-linux-gnuabi64]
image = "ghcr.io/cross-rs/mips64-unknown-linux-gnuabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64-unknown-linux-muslabi64]
image = "ghcr.io/cross-rs/mips64-unknown-linux-muslabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64el-unknown-linux-gnuabi64]
image = "ghcr.io/cross-rs/mips64el-unknown-linux-gnuabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64el-unknown-linux-muslabi64]
image = "ghcr.io/cross-rs/mips64el-unknown-linux-muslabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]
