name: toolchain
description: install rust toolchain

inputs:
  target:
    description: "target triple"
    required: true
  cross:
    description: "install cross-rs"
    required: false
    default: "false"
  components:
    description: "additional components"
    required: false
    default: ""
  write-build-cache:
    description: "write build cache"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    # install rust toolchain
    - name: enable incremental compilation
      run: echo "CARGO_INCREMENTAL=1" >> "$GITHUB_ENV"
      shell: bash

    - name: install toolchain
      uses: dtolnay/rust-toolchain@master
      id: rustup_install
      continue-on-error: true
      with:
        toolchain: nightly
        targets: "${{ inputs.cross == 'false' && inputs.target || 'x86_64-unknown-linux-gnu' }}"
        components: "${{ inputs.components }}"

    - name: cache cross-rs
      if: ${{ inputs.cross == 'true' }}
      uses: actions/cache@v5
      with:
        path: ~/.cargo/bin/cross
        key: cross-${{ runner.os }}
        restore-keys: cross-${{ runner.os }}

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "rustc"
        shared-key: ${{ inputs.target }}
        add-job-id-key: "false"
        add-rust-environment-hash-key: "false"
        env-vars: ""
        # workspace target directories are cached.
        cache-targets: "true"
        # only dependent crates will be cached.
        cache-all-crates: "false"
        cache-workspace-crates: "true"
        cache-bin: "false"
        save-if: ${{ github.ref == 'refs/heads/master' }} # wtf?? adding input.write-build-cache doesn't work

    - name: install cross-rs
      if: ${{ inputs.cross == 'true' }}
      run: |
        if [ ! -f ~/.cargo/bin/cross ]; then
          cargo install cross --git https://github.com/cross-rs/cross
        else
          echo "cross-rs already installed (cached)"
        fi
      shell: bash
