name: toolchain
description: install rust toolchain

inputs:
  target:
    description: "target triple"
    required: true
  cross:
    description: "install cross-rs"
    required: false
    default: "false"
  components:
    description: "additional components"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: cache rustup toolchain
      uses: actions/cache@v5
      with:
        path: |
          ~/.rustup/toolchains
          ~/.rustup/update-hashes
          ~/.rustup/settings.toml
        key: ${{ runner.os }}-rustup-${{ inputs.target }}-${{ hashFiles('rust-toolchain.toml') }}
        restore-keys: |
          ${{ runner.os }}-rustup-${{ inputs.target }}-
          ${{ runner.os }}-rustup-

    - name: cache cargo
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: cache cross-rs
      if: ${{ inputs.cross == 'true' }}
      uses: actions/cache@v5
      with:
        path: ~/.cargo/bin/cross
        key: ${{ runner.os }}-cross-rs-${{ hashFiles('.github/actions/build/*/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-cross-rs-

    - name: cache build target
      uses: actions/cache@v5
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.target }}-target-${{ hashFiles('**/Cargo.lock') }}-
        restore-keys: |
          ${{ runner.os }}-${{ matrix.target }}-target-

    # install rust toolchain
    - name: enable incremental compilation
      run: echo "CARGO_INCREMENTAL=1" >> "$GITHUB_ENV"
      shell: bash

    - name: install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        targets: "${{ inputs.target }}"
        components: "${{ inputs.components }}"

    - name: install cross-rs
      if: ${{ inputs.cross == 'true' }}
      run: |
        if [ ! -f ~/.cargo/bin/cross ]; then
          cargo install cross --git https://github.com/cross-rs/cross
        else
          echo "cross-rs already installed (cached)"
        fi
      shell: bash
